Repository Davoyandun/MENTANA-frontend, pull requests merged in 2024-06, with the labels that each got.

#4 feature/componentes ui
  components.json
  package-lock.json
  package.json
  src/app/page.tsx
  src/shared/components/Accordion.tsx
  src/shared/components/Avatar.tsx
  src/shared/components/Button.tsx
  src/shared/components/DatePicker.tsx
  src/shared/components/ui/accordion.tsx
  src/shared/components/ui/avatar.tsx
  src/shared/components/ui/button.tsx
  src/shared/components/ui/calendar.tsx
  src/shared/components/ui/popover.tsx
  src/shared/context/.gitkeep
  src/shared/hooks/.gitkeep
  src/shared/lib/utils.ts
  src/shared/styles/globals.css
  src/shared/utils/.gitkeep
  tailwind.config.ts
  tsconfig.json
Labels: enhancement

#8 fix/ archivos config shadcn
  src/shared/lib/utils.ts
  src/shared/styles/globals.css
  tailwind.config.js
Labels: fix

#11 feature/ agrega colores de paleta a tailwind.config
  tailwind.config.js
Labels: feature

#19 github action and test without babel
  github/workflows/ci.yml
  jest.config.js
  package-lock.json
  package.json
  setupTests.ts
  src/features/landing/components/Benefits/Benefits.tsx
  src/features/landing/components/StepToUse/stepsForTablet.tsx
  src/shared/components/navbar/logoNavbar.tsx
  src/shared/components/navbar/tests/logoNavbar.test.js
  src/shared/lib/utils.ts
  tsconfig.json
Labels: feature, fix

#26 25 add preguntas frecuentes
  src/app/faq/components/Array.tsx
  src/app/faq/components/faqContent.tsx
  src/app/faq/page.tsx
  src/app/landing/components/AboutUs/aboutUs.tsx
  src/app/landing/components/AboutUs/aboutUsCardDesktop.tsx
  src/app/landing/components/AboutUs/aboutUsCardMobile.tsx
  src/app/landing/components/AboutUs/aboutUsDesktop.tsx
  src/app/landing/components/AboutUs/aboutUsMobile.tsx
  src/app/landing/components/Banner/banner.tsx
  src/app/landing/components/Blog/Blog.tsx
  src/app/landing/components/Blog/cardBlog.tsx
  src/app/landing/components/LandingContent/LandingContent.tsx
  src/app/landing/components/StepToUse/cardStepToStep.tsx
  src/app/landing/components/StepToUse/stepToUse.tsx
  src/app/landing/components/StepToUse/stepsForTablet.tsx
  src/app/landing/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/features/landing/components/AboutUs/aboutUs.tsx
  src/features/landing/pages/landing.tsx
  src/shared/components/ComeBack/comeBack.tsx
  src/shared/components/navbar/Routes/routes.tsx
  src/shared/components/navbar/navbar.tsx
  src/shared/styles/globals.css
Labels: feature

#40 feature[mentana-39]: se agrega blog page
  next.config.mjs
  src/app/blog/page.tsx
  src/app/landing/components/Blog/Blog.tsx
  src/app/landing/components/Blog/cardBlog.tsx
  src/app/layout.tsx
  src/service/api/Blog.ts
  src/shared/components/Buttons/blogButton.tsx
  src/shared/components/navbar/navbar.tsx
  src/shared/context/blog.tsx
  src/shared/context/global.tsx
  src/shared/hooks/.gitkeep
  src/shared/hooks/useBlogContext.ts
  src/shared/interfaces/blog.ts
  tsconfig.json
Labels: feature
